swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /aprobacion_apropiacionAprobar/:
    post:
      tags:
      - aprobacion_apropiacion
      description: Aprobar Apropiacion
      operationId: AprobacionController.Aprobar
      parameters:
      - in: body
        name: body
        description: body for Apropiacion  content
        required: true
        schema:
          $ref: '#/definitions/.Apropiacion'
      responses:
        "201":
          description: '{int} models.InfoSolDisp'
        "403":
          description: body is empty
  /disponibilidad/:
    post:
      tags:
      - disponibilidad
      description: create Disponibilidad
      operationId: DisponibilidadController.Post
      parameters:
      - in: body
        name: body
        description: body for InfoSolDisp content
        required: true
        schema:
          $ref: '#/definitions/models.InfoSolDisp'
      responses:
        "201":
          description: '{int} models.InfoSolDisp'
        "403":
          description: body is empty
  /disponibilidad/AprobarAnulacion:
    post:
      tags:
      - disponibilidad
      description: create Disponibilidad
      operationId: DisponibilidadController.Post
      parameters:
      - in: body
        name: body
        description: body for InfoSolDisp content
        required: true
        schema:
          $ref: '#/definitions/.map[string]interface{}'
      responses:
        "201":
          description: '{int} models.InfoSolDisp'
        "403":
          description: body is empty
  /disponibilidadDisponibilidadByNecesidad/{id}:
    get:
      tags:
      - disponibilidad
      description: get Disponibilidad by id Necesidad
      operationId: DisponibilidadController.DisponibilidadByNecesidad
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.interface{}'
        "403":
          description: ""
  /disponibilidadSolicitudById/{id}:
    get:
      tags:
      - disponibilidad
      description: get SolicitudById
      operationId: DisponibilidadController.SolicitudById
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.InfoSolDisp'
        "403":
          description: ""
  /disponibilidadSolicitudes/:
    get:
      tags:
      - disponibilidad
      description: get Solicitudes
      operationId: DisponibilidadController.Solicitudes
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.InfoSolDisp'
        "403":
          description: ""
  /orden_pago_nomina/:
    post:
      tags:
      - orden_pago_nomina
      description: create Orden_pago_planta
      operationId: OrdenPagoNominaController.Create
      parameters:
      - in: body
        name: body
        description: body for Orden_pago_planta content
        required: true
        schema:
          $ref: '#/definitions/.Orden_pago_planta'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/.Orden_pago_planta'
        "403":
          description: body is empty
  /orden_pago_nominaCrearOPSeguridadSocial:
    post:
      tags:
      - orden_pago_nomina
      description: create Orden Pago Seguridad Social
      operationId: OrdenPagoNominaController.CrearOPSeguridadSocial
      parameters:
      - in: body
        name: body
        description: body for Orden_pago_planta content
        required: true
        schema:
          $ref: '#/definitions/.Orden_pago_planta'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/.Orden_pago_planta'
        "403":
          description: body is empty
  /partida_doble/:
    get:
      tags:
      - partida_doble
      description: get Partidadoble
      operationId: PartidadobleController.GetAll
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.Partidadoble'
        "403":
          description: ""
    post:
      tags:
      - partida_doble
      description: create Partidadoble
      operationId: PartidadobleController.Create
      parameters:
      - in: body
        name: body
        description: body for Partidadoble content
        required: true
        schema:
          $ref: '#/definitions/.Partidadoble'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/.Partidadoble'
        "403":
          description: body is empty
  /partida_doble/{id}:
    get:
      tags:
      - partida_doble
      description: get Partidadoble by id
      operationId: PartidadobleController.GetOne
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.Partidadoble'
        "403":
          description: :id is empty
    put:
      tags:
      - partida_doble
      description: update the Partidadoble
      operationId: PartidadobleController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for Partidadoble content
        required: true
        schema:
          $ref: '#/definitions/.Partidadoble'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.Partidadoble'
        "403":
          description: :id is not int
    delete:
      tags:
      - partida_doble
      description: delete the Partidadoble
      operationId: PartidadobleController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /registro_presupuestal/CargueMasivoPr:
    post:
      tags:
      - registro_presupuestal
      description: create RegistroPresupuestal
      operationId: RegistroPresupuestalController.CargueMasivoPr
      parameters:
      - in: body
        name: body
        description: body for DatosRegistroPresupuestal content
        required: true
        schema:
          $ref: '#/definitions/.DatosRegistroPresupuestal'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Alert'
        "403":
          description: body is empty
  /registro_presupuestal/GetSolicitudesRp:
    get:
      tags:
      - registro_presupuestal
      description: get saldo rp by apropiacion
      operationId: RegistroPresupuestalController.GetSolicitudesRp
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SolicitudRp'
        "403":
          description: :id is empty
  /registro_presupuestal/GetSolicitudesRpById/{id}:
    get:
      tags:
      - registro_presupuestal
      description: get GetSolicitudesRpById by id
      operationId: RegistroPresupuestalController.GetSolicitudesRpById
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.SolicitudRp'
        "403":
          description: :id is empty
  /rubro/GenerarPac/:
    post:
      tags:
      - rubro
      description: Get PAC By Rubro
      operationId: RubroController.GenerarPac
      parameters:
      - in: query
        name: pacData
        description: objeto con fechas del rango del PAC
        required: true
        schema:
          $ref: '#/definitions/.interface{}'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/.interface{}'
        "403":
          description: ""
definitions:
  .Apropiacion:
    type: object
  .DatosRegistroPresupuestal:
    type: object
  .Orden_pago_planta:
    type: object
  .Partidadoble:
    type: object
  .false:
    type: object
  .interface{}:
    type: object
  .map[string]interface{}:
    type: object
  models.Alert:
    title: Alert
    type: object
    properties:
      Body:
        $ref: '#/definitions/13758.0xc420343da0.false'
      Code:
        type: string
      Type:
        type: string
  models.CategoriaCompromiso:
    title: CategoriaCompromiso
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.Compromiso:
    title: Compromiso
    type: object
    properties:
      EstadoCompromiso:
        $ref: '#/definitions/models.EstadoCompromiso'
      FechaFin:
        type: string
        format: string
      FechaInicio:
        type: string
        format: string
      FechaModificacion:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Objeto:
        type: string
      TipoCompromisoTesoral:
        $ref: '#/definitions/models.TipoCompromisoTesoral'
      UnidadEjecutora:
        $ref: '#/definitions/models.UnidadEjecutora'
      Vigencia:
        type: number
        format: double
  models.Dependencia:
    title: Dependencia
    type: object
    properties:
      Id:
        type: integer
        format: int64
      InfoJefeDependencia:
        $ref: '#/definitions/models.InformacionPersonaNatural'
      InfoOrdenador:
        $ref: '#/definitions/models.InformacionPersonaNatural'
      JefeDependencia:
        type: integer
        format: int64
      Nombre:
        type: string
      OrdenadorGasto:
        type: integer
        format: int64
  models.Disponibilidad:
    title: Disponibilidad
    type: object
    properties:
      DatosNecesidad:
        $ref: '#/definitions/models.Necesidad'
      Estado:
        $ref: '#/definitions/models.EstadoDisponibilidad'
      FechaRegistro:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      NumeroDisponibilidad:
        type: number
        format: double
      Responsable:
        type: integer
        format: int64
      Solicitud:
        type: integer
        format: int64
      Vigencia:
        type: number
        format: double
  models.EstadoCompromiso:
    title: EstadoCompromiso
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.EstadoDisponibilidad:
    title: EstadoDisponibilidad
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.InfoSolDisp:
    title: InfoSolDisp
    type: object
    properties:
      DependenciaDestino:
        $ref: '#/definitions/models.Dependencia'
      DependenciaSolicitante:
        $ref: '#/definitions/models.Dependencia'
      SolicitudDisponibilidad:
        $ref: '#/definitions/models.SolicitudDisponibilidad'
  models.InformacionPersonaNatural:
    title: InformacionPersonaNatural
    type: object
    properties:
      Cargo:
        type: string
      DigitoVerificacion:
        type: number
        format: double
      Especialidad:
        type: string
      Genero:
        type: string
      Id:
        type: integer
        format: int64
      MontoCapitalAutorizado:
        type: number
        format: double
      Perfil:
        $ref: '#/definitions/models.ParametroEstandar'
      PrimerApellido:
        type: string
      PrimerNombre:
        type: string
      Profesion:
        type: string
      SegundoApellido:
        type: string
      SegundoNombre:
        type: string
      TipoDocumento:
        $ref: '#/definitions/models.ParametroEstandar'
  models.InformacionProveedor:
    title: InformacionProveedor
    type: object
    properties:
      Id:
        type: integer
        format: int64
      NomProveedor:
        type: string
      NumDocumento:
        type: number
        format: double
      Tipopersona:
        type: string
  models.ModalidadSeleccion:
    title: ModalidadSeleccion
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.Necesidad:
    title: Necesidad
    type: object
    properties:
      DatosDependenciaSolicitante:
        $ref: '#/definitions/models.Dependencia'
      Id:
        type: integer
        format: int64
      Justificacion:
        type: string
      ModalidadSeleccion:
        $ref: '#/definitions/models.ModalidadSeleccion'
      Numero:
        type: integer
        format: int64
      Objeto:
        type: string
      UnidadEjecutora:
        type: integer
        format: int64
      Valor:
        type: number
        format: double
      Vigencia:
        type: number
        format: double
  models.ParametroEstandar:
    title: ParametroEstandar
    type: object
    properties:
      ClaseParametro:
        type: string
      DescripcionParametro:
        type: string
      Id:
        type: integer
        format: int64
      ValorParametro:
        type: string
  models.SolicitudDisponibilidad:
    title: SolicitudDisponibilidad
    type: object
    properties:
      Expedida:
        type: boolean
      FechaSolicitud:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Necesidad:
        $ref: '#/definitions/models.Necesidad'
      Numero:
        type: integer
        format: int64
      Vigencia:
        type: number
        format: double
  models.SolicitudRp:
    title: SolicitudRp
    type: object
    properties:
      Cdp:
        type: integer
        format: int64
      Compromiso:
        type: integer
        format: int64
      DatosCompromiso:
        $ref: '#/definitions/models.Compromiso'
      DatosDisponibilidad:
        $ref: '#/definitions/models.Disponibilidad'
      DatosProveedor:
        $ref: '#/definitions/models.InformacionProveedor'
      Expedida:
        type: boolean
      FechaSolicitud:
        type: string
        format: string
      Id:
        type: integer
        format: int64
      Masivo:
        type: boolean
      NumeroContrato:
        type: string
      Rubros:
        type: array
        items:
          $ref: '#/definitions/6887.0xc420342d80.false'
      Vigencia:
        type: integer
        format: int64
      VigenciaContrato:
        type: string
  models.TipoCompromisoTesoral:
    title: TipoCompromisoTesoral
    type: object
    properties:
      CategoriaCompromiso:
        $ref: '#/definitions/models.CategoriaCompromiso'
      Descripcion:
        type: string
      EstadoActivo:
        type: boolean
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
  models.UnidadEjecutora:
    title: UnidadEjecutora
    type: object
    properties:
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
tags:
- name: registro_presupuestal
  description: |
    RegistroPresupuestalController operations for RegistroPresupuestal
- name: partida_doble
  description: |
    PartidadobleController operations for Partidadoble
- name: orden_pago_nomina
  description: |
    OrdenPagoNominaController operations for Orden_pago_planta
